name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &
      - name: Wait for server to start
        run: sleep 10
     


      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'graphql-ejemplo1'
          heroku_email: 'nfsalguero@uce.edu.ec'